# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

os.chdir(os.path.dirname(os.path.dirname(__file__)))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, name):
        self.name = name
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 502)
        self.chat_widget = QtWidgets.QWidget(parent=MainWindow)
        self.chat_widget.setObjectName("chat_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.chat_widget)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chat_layout = QtWidgets.QHBoxLayout()
        self.chat_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.chat_layout.setObjectName("chat_layout")
        self.left_widget = QtWidgets.QVBoxLayout()
        self.left_widget.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.left_widget.setObjectName("left_widget")
        self.left_layout = QtWidgets.QHBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.chat_list = QtWidgets.QLabel(parent=self.chat_widget)
        self.chat_list.setObjectName("chat_list")
        self.left_layout.addWidget(self.chat_list)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.left_layout.addItem(spacerItem)
        self.add_friend_button = QtWidgets.QPushButton(parent=self.chat_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_friend_button.sizePolicy().hasHeightForWidth())
        self.add_friend_button.setSizePolicy(sizePolicy)
        self.add_friend_button.setDefault(False)
        self.add_friend_button.setObjectName("add_friend_button")
        self.left_layout.addWidget(self.add_friend_button)
        self.add_group_button = QtWidgets.QPushButton(parent=self.chat_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_group_button.sizePolicy().hasHeightForWidth())
        self.add_group_button.setSizePolicy(sizePolicy)
        self.add_group_button.setObjectName("add_group_button")
        self.left_layout.addWidget(self.add_group_button)
        self.left_layout.setStretch(0, 5)
        self.left_layout.setStretch(3, 1)
        self.left_widget.addLayout(self.left_layout)
        self.user_list_widget = QtWidgets.QListWidget(parent=self.chat_widget)
        self.user_list_widget.setObjectName("user_list_widget")
        self.left_widget.addWidget(self.user_list_widget)
        self.chat_layout.addLayout(self.left_widget)
        self.right_widge = QtWidgets.QVBoxLayout()
        self.right_widge.setObjectName("right_widge")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.name_chat = QtWidgets.QLabel(parent=self.chat_widget)
        self.name_chat.setObjectName("name_chat")
        self.horizontalLayout_4.addWidget(self.name_chat)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.detail = QtWidgets.QPushButton(parent=self.chat_widget)
        self.detail.setStyleSheet("\n"
"min-width:10px;\n"
"min-height:10px;")
        self.detail.setAutoRepeatInterval(100)
        self.detail.setObjectName("detail")
        self.horizontalLayout_4.addWidget(self.detail)
        self.right_widge.addLayout(self.horizontalLayout_4)
        self.chat_display = QtWidgets.QTextEdit(parent=self.chat_widget)
        self.chat_display.setObjectName("chat_display")
        self.right_widge.addWidget(self.chat_display)
        self.right_layout = QtWidgets.QHBoxLayout()
        self.right_layout.setObjectName("right_layout")
        self.emoji = QtWidgets.QPushButton(parent=self.chat_widget)
        self.emoji.setStyleSheet("min-width: 30px;\n"
"max-width: 30px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"image:url(./image/smiley.png);\n"
"background-color: transparent;\n"
"border: none;")
        self.emoji.setText("")
        self.emoji.setObjectName("emoji")
        self.right_layout.addWidget(self.emoji)
        self.image = QtWidgets.QPushButton(parent=self.chat_widget)
        self.image.setStyleSheet("min-width: 30px;\n"
"max-width: 30px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"image:url(./image/image-gallery.png);\n"
"background-color: transparent;\n"
"border: none;")
        self.image.setText("")
        self.image.setObjectName("image")
        self.right_layout.addWidget(self.image)
        self.video = QtWidgets.QPushButton(parent=self.chat_widget)
        self.video.setMouseTracking(False)
        self.video.setAcceptDrops(False)
        self.video.setStyleSheet("min-width: 30px;\n"
"max-width: 30px;\n"
"min-height: 20px;\n"
"max-height: 20px;\n"
"image:url(./image/cam-recorder.png);\n"
"background-color: transparent;\n"
"border: none;")
        self.video.setText("")
        self.video.setObjectName("video")
        self.right_layout.addWidget(self.video)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.right_layout.addItem(spacerItem2)
        self.right_widge.addLayout(self.right_layout)
        self.input_field = QtWidgets.QTextEdit(parent=self.chat_widget)
        self.input_field.setObjectName("input_field")
        self.right_widge.addWidget(self.input_field)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.send_button = QtWidgets.QPushButton(parent=self.chat_widget)
        self.send_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_button.sizePolicy().hasHeightForWidth())
        self.send_button.setSizePolicy(sizePolicy)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_3.addWidget(self.send_button)
        self.right_widge.addLayout(self.horizontalLayout_3)
        self.right_widge.setStretch(1, 6)
        self.right_widge.setStretch(3, 2)
        self.chat_layout.addLayout(self.right_widge)
        self.chat_layout.setStretch(0, 1)
        self.chat_layout.setStretch(1, 2)
        self.horizontalLayout_6.addLayout(self.chat_layout)
        MainWindow.setCentralWidget(self.chat_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"网络聊天室——{self.name}"))
        self.chat_list.setText(_translate("MainWindow", "聊天列表"))
        self.add_friend_button.setText(_translate("MainWindow", "添加好友"))
        self.add_group_button.setText(_translate("MainWindow", "添加群聊"))
        self.name_chat.setText(_translate("MainWindow", "名称"))
        self.detail.setText(_translate("MainWindow", "..."))
        self.send_button.setText(_translate("MainWindow", "发送"))
