# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 376)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(4, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.video = QtWidgets.QWidget(parent=Dialog)
        self.video.setObjectName("video")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.video)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.from_user = QtWidgets.QLabel(parent=self.video)
        self.from_user.setObjectName("from_user")
        self.horizontalLayout.addWidget(self.from_user)
        self.to_user = QtWidgets.QLabel(parent=self.video)
        self.to_user.setObjectName("to_user")
        self.horizontalLayout.addWidget(self.to_user)
        self.verticalLayout_2.addWidget(self.video)
        self.bottom = QtWidgets.QHBoxLayout()
        self.bottom.setSpacing(0)
        self.bottom.setObjectName("bottom")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottom.addItem(spacerItem)
        self.button = QtWidgets.QPushButton(parent=Dialog)
        self.button.setDefault(True)
        self.button.setObjectName("button")
        self.bottom.addWidget(self.button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottom.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.bottom)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.from_user.setText(_translate("Dialog", "from_user"))
        self.to_user.setText(_translate("Dialog", "to_user"))
        self.button.setText(_translate("Dialog", "end"))
